rango/urls.py
from django.urls import path
from rango import views 

app_name='rango'

urlpatterns=[
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    #path('index/', views.index, name='index')
    ]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #'' when thre is nothing after http://127.0.0.1:8000/
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    #The thingy above maps any URLs starting with rango/ to be handled by rango
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models

class Category(models.Model):
    name=models.CharField(max_length=128, unique=True)
    views=models.IntegerField(default=0)
    likes=models.IntegerField(default=0)
    class Meta:
        verbose_name_plural= 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category=models.ForeignKey(Category, on_delete=models.CASCADE)
    title=models.CharField(max_length=128)
    url=models.URLField()
    views=models.IntegerField(default=0)

    def __str__(self):
        return self.title

rango/forms.py
from django import forms
from rango.models import Page, Category
from django.contrib.auth.models import User
from rango.models import UserProfile

class CategoryForm(forms.ModelForm):
    name=forms.CharField(max_length=Category.NAME_MAX_LENGTH, help_text="Please enter the category name.")
    views= forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta: 
        model = Category 
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH, help_text="Enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page 
        exclude = ('category',) 

    def clean(self):
        cleaned_data=self.cleaned_data
        url= cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url=f'http://{url}'
            cleaned_data['url']=url
        return cleaned_data

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model=User
        fields=('username','email','password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model=UserProfile
        fields=('website','picture')

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    context_dict = {'boldmessage': 'Crunchy, creamy, cookie, candy, cupcake!'}
    return render(request, 'rango/index.html', context=context_dict)



def about(request):
    return render(request, 'rango/about.html')

templates/rango/about.html
<!DOCTYPE html>
{% load staticfiles %}

<html>

    <head>

        <title>Rango</title>

    </head>



    <body>

        <h1>Rango says...</h1>

        <div>

            here is the about page. <br />

            This tutorial has been put together by David Maxwell.<br />

        </div>

        <div>

            <a href="/rango/">Index</a><br />

            <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />

            <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat" />

        </div>

    </body>



</html>

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}    

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}

<div>
    <form id="category_form" method="post" action="{% url 'rango:add_category' %}">

        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}

            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}

        {% endfor %}
        <input type="submit" name="submit" value="Create Category" />
    </form>
</div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}    

{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}

<div>
    <form id="add_page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}

            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}

        {% endfor %}
        <input type="submit" name="submit" value="Add Page" />
    </form>
</div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>Rango -
            {% block title_block %} 
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>

    <body>

        <div>
            {% block body_block %} 
            {% endblock %}
        </div>
        
        <div>
            {% block sidebar_block %}
            {% get_category_list category %}
            {% endblock %}
        </div>
        
        <hr />
        <div>
            <ul>
                {% if user.is_authenticated %}

                    <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                    <li><a href="{% url 'rango:logout' %}">Logout</a></li>
                    <li>><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>

                {% else %}
                    <li><a href="{% url 'rango:register' %}">Sign Up</a></li> 
                    <li><a href="{% url 'rango:login' %}">Login</a></li>
                {% endif %}
                    <li><a href="{% url 'rango:about' %}">About</a></li> 
                    <li><a href="{% url 'rango:index' %}">Index</a></li> 
        
            </ul>
        </div>
    
    </body>
</html>

templates/rango/categories.html
<ul>
{% if categories %}
    {% for c in categories %}
        {% if c == current_category %}
        <li>
        <strong>
            <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
        </strong>
        </li>
        {% else %}
        <li>
            <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a> </li> 
        </li>
        {% endif %}
    {% endfor %}
{% else %}
    <li><strong>There are no categories present.</strong></li> 
{% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}

    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}

{% endblock %}


{% block body_block %}

    {% if category %}
    <h1>{{ category.name }}</h1>
    {% if pages %}

    <ul>

        {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}

    </ul>

    {% else %}
    <strong>No pages currently in category.</strong>
    {% endif %}

    {% if user.is_authenticated %}
    <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br />
    {% endif %}

    {% else %}
    The specified category does not exist.
    {% endif %}

{% endblock %}

templates/rango/index.html
<!DOCTYPE html>



{% load staticfiles %}



<html>



    <head>

        <title>Rango</title>

    </head>



    <body>

        <h1>Rango says...</h1>

        <div>

            hey there partner! <br />

            <strong>{{ boldmessage }}</strong><br />

        </div>

        <div>

            <a href="/rango/about/">About</a><br />

            <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />

        </div>

    </body>



</html>

templates/rango/login.html
{% extends 'rango/base.html' %} 
{% load staticfiles %}

{% block title_block %}
    Login 
{% endblock %}

{% block body_block %} 

<h1>Login to Rango</h1> 
<form id="login_form" method="post" action="{% url 'rango:login' %}"> 
    {% csrf_token %} 
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" /> 
    <br /> 
    <input type="submit" value="submit" /> 
</form> 
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
<h1>Register for Rango</h1>

{% if registered %}

Rango says: <strong>thank you for registering!</strong>
<a href="{% url 'rango:index' %}">Return to the homepage.</a><br />

{% else %}
Rango says: <strong>register here!</strong><br />

<form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">

    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="submit" value="Register" />

</form>

{% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
<h1>Restricted Page</h1>
You have successfully logged in. <br />

{% endblock %}